a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Products;
using a5pwt_ctvrtek.Application.ViewModels.Products;
using a5pwt_ctvrtek.Areas.Admin.Controllers.Common;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Areas.Admin.Controllers
{
    public class ProductsController : AdminController
    {
        private readonly IProductApplicationService _productApplicationService;

        public ProductsController(IProductApplicationService productApplicationService)
        {
            _productApplicationService = productApplicationService;
        }

        public IActionResult Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }

        public IActionResult Edit(int id)
        {
            var vm = _productApplicationService.GetProductViewModel(id);
            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
           var product = _productApplicationService.Edit(model);

            return Json(product);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(ProductViewModel model)
        {
            var product =_productApplicationService.Insert(model);

            //return RedirectToAction(nameof(Index));
            return Json(product);
        }

        public IActionResult Delete(ProductViewModel model)
        {
            _productApplicationService.Delete(model);

            return RedirectToAction(nameof(Index));
        }
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/UserGolden/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Products;
using a5pwt_ctvrtek.Areas.UserGolden.Controllers.Common;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Areas.UserGolden
{
	public class ProductsController : UserGoldenController
	{
		private readonly IProductApplicationService _productApplicationService;

		public ProductsController(IProductApplicationService productApplicationService)
		{
			_productApplicationService = productApplicationService;
		}
		public IActionResult Index()
		{
			var vm = _productApplicationService.GetIndexViewModel();
			return View(vm);
		}
		public IActionResult Detail(int id)
		{
			var vm = _productApplicationService.GetProductViewModel(id);
			return View(vm);
		}
	}
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/UserSilver/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Products;
using a5pwt_ctvrtek.Areas.UserSilver.Controllers.Common;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Areas.UserSilver.Controllers
{
    public class ProductsController : UserSilverController
    {
		private readonly IProductApplicationService _productApplicationService;

		public ProductsController(IProductApplicationService productApplicationService)
		{
			_productApplicationService = productApplicationService;
		}
		public IActionResult Index()
		{
			var vm = _productApplicationService.GetIndexViewModel();
			return View(vm);
		}
		public IActionResult Detail(int id)
		{
			var vm = _productApplicationService.GetProductViewModel(id);
			return View(vm);
		}
	}
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Carts;
using a5pwt_ctvrtek.Application.ApplicationServices.Security;
using a5pwt_ctvrtek.Domain.Constants;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartApplicationService _cartApplicationService;
        private readonly IApplicationSecurityService _securityApplicationService;

        public CartsController(ICartApplicationService cartApplicationService,
            IApplicationSecurityService securityApplicationService)
        {
            _cartApplicationService = cartApplicationService;
            _securityApplicationService = securityApplicationService;
        }

		public async Task<IActionResult> Index()
		{
			var vm = _cartApplicationService.GetIndexViewModel(GetOrCreateTrackingCode());
			var user = await _securityApplicationService.GetCurrentUser(User);
			if (user != null)
			{
				vm.UserID = user.Id;
				vm.UserEmail = user.Email;
			}

			return View(vm);
		}

		[HttpPost]
		public JsonResult AddToCart(int id, int amount)
		{
			var cartItem = _cartApplicationService.AddToCart(id, amount, GetOrCreateTrackingCode());

			return Json(cartItem);
		}

		[HttpPost]
		public JsonResult RemoveFromCart(int id)
		{
			_cartApplicationService.RemoveFromCart(id, GetOrCreateTrackingCode());
			return Json("success");
		}

		private string GetOrCreateTrackingCode()
		{
			var utc = Request.Cookies[Cookies.UserTrackingCode];
			if (utc != null)
				return utc;

			var guid = Guid.NewGuid().ToString();
			var options = new CookieOptions();
			options.Expires = DateTime.Now.AddYears(1);

			Response.Cookies.Append(Cookies.UserTrackingCode, guid, options);
			return guid;
		}
	}
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Products;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductApplicationService _productApplicationService;

        public ProductsController(IProductApplicationService productApplicationService)
        {
            _productApplicationService = productApplicationService;
        }
        public IActionResult Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }
        public IActionResult Detail(int id)
        {
            var vm = _productApplicationService.GetProductViewModel(id);
            return View(vm);
        }
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/UserGolden/Views/Products/Detail.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Products.ProductViewModel
@using  a5pwt_ctvrtek.Domain.Constants

@{
    ViewData["Title"] = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>@Model.Name</h4>
    <hr />
    <div class="row">
        <div class="col-md-5">
            <img src="@Model.ImageURL" alt="@Model.Name" style="max-height:200px;" />
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>

                    @Html.DisplayNameFor(model => model.Price)&gt; 00 Pcs &lt; 10 Pcs
                </dt>
                <dd>
                    @{decimal basePrice = Model.Price * Pricing.SecondClass; }
                    @Html.DisplayFor(model => basePrice)
                </dd>
                <!-- 10-20 -->
                <dt>
                    
                    @Html.DisplayNameFor(model => model.Price)&gt; 10 Pcs &lt; 20 Pcs
                </dt>
                <dd>

                    @{
                        decimal price1 = basePrice * Pricing.FirstClass;
                        price1.ToString("0.00");
                    }
                    @Html.DisplayFor(model => price1)

                </dd>
                <!-- 20-30 -->
                <dt>
                    @Html.DisplayNameFor(model => model.Price)&gt; 20 Pcs &lt; 30 Pcs
                </dt>
                <dd>
                    @{
                        decimal price2 = basePrice * Pricing.SecondClass;
                        price1.ToString("0.00");
                    }
                    @Html.DisplayFor(model => price2)
                </dd>
                <!-- 20-30 -->
                <dt>
                    @Html.DisplayNameFor(model => model.Price)&gt; 30 Pcs &lt; &#8734;&#8734;  Pcs
                </dt>
                <dd>
                    @{
                        decimal price3 = basePrice * Pricing.ThirdClass;
                        price1.ToString("0.00");
                    }
                    @Html.DisplayFor(model => price3)
                </dd>
            </dl>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="number" value="1" />
            <button id="add-to-cart" data-id="@Model.ID" class="btn btn-primary">Přidat do košíku</button>
            <div class="alert alert-success" id="success-alert" style="display:none;">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong>Added!</strong>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>
    $(document).ready(() => {
        $('#add-to-cart').click(addToCart);
    });

    function addToCart() {
        var id = $(this).data('id');
        var amount = $(this).closest('div').find('input').val();

        $.ajax({
            method: 'POST',
            url: '@Url.Action("AddToCart", "Carts")',
            data: {id: id, amount: amount},
            success: function () {
                $("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
                    $("#success-alert").slideUp(500);
                });
            }
        })
    }
    </script>
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/UserGolden/Views/Products/Index.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Products.IndexViewModel
@using a5pwt_ctvrtek.Domain.Constants;
@{
    ViewData["Title"] = "Index";
    
}

<h2>Index</h2>
<div class="row">
    @foreach (var product in Model.Products)
    {
        <div class="col-xs-4">
            <div class="thumbnail">
                <img src="@product.ImageURL" alt="@product.Name" />
                <div class="caption">
                    <h3>@product.Name</h3>
                    <a class="btn btn-primary" asp-controller="Products" asp-action="Detail" asp-route-id="@product.ID">Detail</a>
                    <p>
                        @{
                            decimal price = product.Price * Pricing.SecondClass;
                        }
                        @price Kč
                    </p>
                </div>
            </div>
        </div>
    }
</div>